/**
 * @module agent/types
 * @description Core type definitions for the aouo agent framework.
 *
 * Defines the foundational interfaces used throughout the agent runtime:
 * - {@link Message} — Conversation history format
 * - {@link LLMProvider} — LLM provider abstraction
 * - {@link ToolDefinition} — Tool registration and execution
 * - {@link Adapter} — Platform adapter interface (Telegram, CLI, etc.)
 *
 * These types are intentionally domain-agnostic. Domain-specific extensions
 * belong in pack code, not here.
 */

import type { AouoConfig } from '../config/defaults.js';

// ── Conversation History ─────────────────────────────────────────────────────

/**
 * Represents an attached file (e.g., an image) for multimodal input.
 *
 * Transient data carried through the ReAct loop but never persisted
 * to SQLite. Before saving messages, the Agent degrades file-bearing
 * messages to plain text placeholders.
 */
export interface MessageFile {
  /** Absolute path to the file on disk. */
  path: string;
  /** MIME type of the file (e.g., 'image/jpeg'). */
  mimeType: string;
}

/**
 * Represents a single message in the conversation history.
 *
 * Messages are persisted to the session database and replayed on each
 * LLM call. The `role` field determines how the message is interpreted
 * by the provider.
 */
export interface Message {
  /** The role of the message sender in the conversation. */
  role: 'system' | 'user' | 'assistant' | 'tool';
  /** Text content of the message. Optional for tool-call-only assistant turns. */
  content?: string;
  /** Attached files for native multimodal input. Transient — never persisted. */
  files?: MessageFile[];
  /** Tool calls requested by the assistant (present when role is 'assistant'). */
  toolCalls?: ToolCall[];
  /** ID linking this tool result to the original tool call (present when role is 'tool'). */
  toolCallId?: string;
  /** Name of the tool that produced this result (present when role is 'tool'). */
  toolName?: string;
  /** Provider-native response parts preserved for replay and debugging. */
  _rawParts?: unknown;
}

/**
 * Represents a tool call requested by the LLM.
 *
 * Each tool call has a unique ID (generated at parse time) used to
 * correlate tool results back to the originating call.
 */
export interface ToolCall {
  /** Unique identifier for this tool call instance. */
  id: string;
  /** Name of the tool to execute (must match a registered tool). */
  name: string;
  /** Arguments to pass to the tool's execute function. */
  args: Record<string, unknown>;
}

/**
 * Structured result returned from a tool dispatch operation.
 */
export interface ToolDispatchResult {
  /** The string content returned by the tool execution. */
  content: string;
  /** True if the tool execution resulted in an error. */
  isError: boolean;
}

// ── LLM Provider ─────────────────────────────────────────────────────────────

/**
 * Token usage statistics from an LLM API call.
 *
 * Used for cost tracking, monitoring, and context management decisions.
 */
export interface TokenUsage {
  /** Total input tokens (includes cached). */
  promptTokens: number;
  /** Output tokens generated by the model. */
  completionTokens: number;
  /** Sum of all token types. */
  totalTokens: number;
  /** Tokens served from implicit context cache (usually cheaper). */
  cachedTokens?: number;
  /** Reasoning/thinking tokens when the provider reports them. */
  thoughtsTokens?: number;
}

/**
 * Represents a response from an LLM provider's chat completion call.
 *
 * A response can contain text content, tool calls, or both.
 */
export interface LLMResponse {
  /** Text content generated by the model. */
  content?: string;
  /** Tool calls the model wants to execute. */
  toolCalls?: ToolCall[];
  /** Token usage statistics for this API call. */
  usage?: TokenUsage;
  /** Provider-native response parts preserved for replay or debugging. */
  rawModelParts?: unknown;
  /** API call duration in milliseconds as reported by the provider. */
  durationMs?: number;
}

/**
 * Additional runtime options for the LLM chat completion call.
 */
export interface ChatOptions {
  /** Session ID used for prompt caching and tracing. */
  sessionId?: string;
}

/**
 * Standard interface for all LLM providers (e.g., OpenAI, Gemini).
 *
 * Each provider implementation handles API-specific serialization,
 * response parsing, and error recovery.
 */
export interface LLMProvider {
  /** The unique identifier for the provider (e.g., 'openai', 'gemini'). */
  readonly name: string;

  /**
   * Executes a chat completion request against the LLM provider.
   *
   * @param messages - Full conversation history including the system prompt.
   * @param tools - Available tools the model is allowed to call.
   * @param config - Global agent configuration settings.
   * @param options - Additional runtime options for the request.
   * @returns A promise resolving to the model's response.
   */
  chat(
    messages: Message[],
    tools: ToolSchema[],
    config: AouoConfig,
    options?: ChatOptions,
  ): Promise<LLMResponse>;
}

// ── Platform Adapter ─────────────────────────────────────────────────────────

export type AdapterMessageType =
  | 'text'
  | 'audio'
  | 'voice'
  | 'document'
  | 'keyboard'
  | 'quiz'
  | 'edit'
  | 'delete'
  | 'react'
  | 'action'
  | 'countdown'
  | 'paginate';

/**
 * Platform-neutral outbound message intent.
 *
 * Tools and skills express what they want to send; adapters decide how to
 * render it on their platform or how to degrade when a feature is unsupported.
 */
export interface AdapterMessagePayload {
  type: AdapterMessageType;
  text?: string;
  url?: string;
  buttons?: string[][];
  options?: string[];
  correct?: number;
  explanation?: string;
  messageId?: string | number;
  replyTo?: string | number;
  tag?: string;
  emoji?: string;
  action?: string;
  parseMode?: string;
  seconds?: number;
  expireText?: string;
}

/**
 * Result returned by an adapter after handling an outbound message intent.
 */
export interface AdapterMessageResult {
  ok: boolean;
  messageId?: string | number | null;
  pollId?: string;
  pageCount?: number;
  sentContent?: boolean;
  error?: string;
  [key: string]: unknown;
}

/**
 * Per-feature declaration of what an adapter can natively render.
 *
 * Used by the message-dispatch tool tier to decide whether to pass a
 * payload through to the adapter unchanged or to degrade it to a more
 * universally supported shape (typically `text` or `keyboard`). Every
 * field is independent because platforms vary along several axes:
 * Telegram has native polls but Discord doesn't; Discord has native
 * threads but Feishu uses interactive cards; etc.
 *
 * An undefined `capabilities` on the {@link Adapter} interface is
 * treated as "all features supported" so legacy adapters and test
 * stubs continue to work without modification.
 */
export interface AdapterCapabilities {
  /** Native quiz / poll widget with answer correlation. */
  readonly quiz: boolean;
  /** Native voice-note bubble (typically OGG/Opus). */
  readonly voice: boolean;
  /** Audio file attachment with controls. */
  readonly audio: boolean;
  /** Live in-place countdown via message edits. */
  readonly countdown: boolean;
  /** Client-side pagination over multiple pages via inline buttons. */
  readonly paginate: boolean;
  /** Emoji reactions on a target message. */
  readonly react: boolean;
  /** In-place message editing (powers streaming token replies). */
  readonly editMessage: boolean;
}

/**
 * Default capability profile assumed for adapters that omit the
 * `capabilities` field. Mirrors what the Telegram adapter natively
 * supports — chosen so today's behavior is unchanged when an adapter
 * is migrated incrementally to declare its capabilities.
 */
export const FULL_ADAPTER_CAPABILITIES: AdapterCapabilities = {
  quiz: true,
  voice: true,
  audio: true,
  countdown: true,
  paginate: true,
  react: true,
  editMessage: true,
};

/**
 * Platform adapter interface for user interaction.
 *
 * The Agent remains platform-agnostic by communicating exclusively through
 * this interface. Each target platform (Telegram, CLI, etc.) must implement
 * its own adapter.
 */
export interface Adapter {
  /** Platform identifier used for runtime branching (e.g., 'telegram', 'cli'). */
  readonly platform: string;

  /**
   * Declarative description of which rich-message features this adapter
   * renders natively. The message-dispatch tool reads this to decide
   * whether to degrade a payload before handing it to {@link dispatchMessage}.
   * Omit to mean "all features supported" (matches legacy behavior).
   */
  readonly capabilities?: AdapterCapabilities;

  /**
   * Sends a text response to the user.
   *
   * @param content - The text message to send.
   */
  reply(content: string): Promise<void>;

  /**
   * Displays a tool call notification to the user.
   * Optional — used by UIs providing real-time tool execution feedback.
   *
   * @param toolName - The name of the tool being called.
   * @param args - The arguments passed to the tool.
   */
  showToolCall?(toolName: string, args: Record<string, unknown>): void;

  /**
   * Displays the result of a tool execution to the user.
   * Optional — used by UIs showing tool execution outcomes.
   *
   * @param toolName - The name of the executed tool.
   * @param result - The string output or error message from the tool.
   * @param isError - Boolean indicating if the execution failed.
   */
  showToolResult?(toolName: string, result: string, isError: boolean): void;

  /**
   * Requests user approval for a sensitive operation.
   *
   * @param description - Detailed description of the operation needing approval.
   * @returns A promise resolving to the user's decision.
   */
  requestApproval(description: string): Promise<'allow' | 'deny' | 'always'>;

  /**
   * Prompts the user to pick from a set of choices via the native UI.
   * Optional — not all platforms support interactive selection.
   *
   * @param description - The prompt describing what the user is choosing.
   * @param choices - An array of string options to present to the user.
   * @returns A promise resolving to the selected choice.
   */
  requestChoice?(description: string, choices: string[]): Promise<string>;

  /**
   * Sends a structured outbound message intent through the platform.
   * Optional — adapters without rich-message support can rely on reply().
   */
  dispatchMessage?(message: AdapterMessagePayload): Promise<AdapterMessageResult>;
}

// ── Tool System ──────────────────────────────────────────────────────────────

/**
 * JSON Schema definition for a tool's input parameters.
 *
 * Adheres to the OpenAPI/JSON Schema subset supported by standard LLM
 * function calling APIs.
 */
export interface ToolParameterSchema {
  type: 'object';
  properties: Record<
    string,
    {
      type: string;
      description?: string;
      default?: unknown;
      enum?: unknown[];
      items?: { type: string };
    }
  >;
  required?: string[];
}

/**
 * Compact tool schema used in LLM function calling declarations.
 */
export interface ToolSchema {
  name: string;
  description: string;
  parameters: ToolParameterSchema;
}

/**
 * Execution context passed to tool handlers.
 *
 * Grants tools access to the platform adapter, agent configuration,
 * session details, and pack context needed for their operation.
 */
export interface ToolContext {
  /** The active platform adapter for interacting with the user. */
  adapter: Adapter;
  /** The current agent configuration. */
  config: AouoConfig;
  /** The active session ID (internal UUID). */
  sessionId?: string;
  /** The external session key (e.g., 'tg:5496437870'). */
  sessionKey?: string;
  /** The name of the pack that triggered this tool call, if any. */
  pack?: string;
}

/**
 * Defines a tool that the agent can execute.
 *
 * Tools are registered at startup and discovered dynamically by the
 * agent during the ReAct loop.
 *
 * @example
 * ```typescript
 * const myTool: ToolDefinition = {
 *   name: 'my_tool',
 *   description: 'Does something useful.',
 *   parameters: { type: 'object', properties: {}, required: [] },
 *   async execute(args, ctx) { return JSON.stringify({ ok: true }); },
 * };
 * ```
 */
export interface ToolDefinition {
  /** Optional platform allowlist. If omitted, the tool is available on every adapter. */
  platforms?: string[];
  /** Unique name of the tool, used in LLM function declarations. */
  name: string;
  /** Human-readable description guiding the LLM on when to use this tool. */
  description: string;
  /** JSON Schema defining the input parameters for the tool. */
  parameters: ToolParameterSchema;
  /** Maximum execution time in ms before the tool is aborted. Defaults to 30,000. */
  timeoutMs?: number;
  /**
   * Executes the tool's primary logic.
   *
   * @param args - Structured arguments provided by the LLM.
   * @param context - Execution context with adapter, config, and session info.
   * @returns A promise resolving to a serialized string result.
   */
  execute: (args: Record<string, unknown>, context: ToolContext) => Promise<string>;
}

// Re-export config type for downstream consumers
export type { AouoConfig } from '../config/defaults.js';
